version: "2.13"
services:
  backend:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: Covid19-statistics
    networks:
      - Covid19-statistics

networks:
  Covid19-statistics:
    driver: bridge