version: "3.8"
services:
  backend:
    build:
      context: ./src/Backend
      dockerfile: Dockerfile
    hostname: backend
    ports:
      - "8000:8000"
    container_name: Covid19-statistics

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  python:
    build: 
      context: ./src/DataBase
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    links:
      - mongodb

  frontend:
    build: 
      context: ./src/Frontend
      dockerfile: Dockerfile
    hostname: frontend
    ports:
      - 8501:8501
    container_name: Covid19-statistics-frontend
    depends_on:
      - mongodb
  

