version: "3.8"
services:
  backend:
    build:
      context: ./src/Backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: Covid19-statistics
      

  frontend:
    build: 
      context: ./src/Frontend
      dockerfile: Dockerfile
    ports:
      - 8501:8501
    container_name: Covid19-statistics-frontend
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DBNAME: Covid19
      MONGO_USERNAME: sahar
      MONGO_PASSWORD: sahar
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"  
